branch-defaults:
  master:
    environment: ENV-my_project
global:
  application_name: my_project
  default_ec2_keyname: orchard_admin
  default_platform: null
  default_region: null
  profile: null
  sc: git
deploy:
  artifact: my_project.zip
